---
app:
  serviceType: NodePort
  image: fluentintegrations/flintx-inventory:1.3.0
  name: flintx-inventory
  version: 1.3.0
  namespace: flintx
  host: flintx-inventory.co
  port: 8085
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 30
    timeoutSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 30
    httpGet:
      path: /q/health/live
      scheme: HTTP
      port: 8085
  readinessProbe:
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 45
    successThreshold: 1
    initialDelaySeconds: 45
    httpGet:
      path: /q/health/ready
      scheme: HTTP
      port: 8085