---
app:
  serviceType: ClusterIP
  image: fluentintegrations/flintx-auth:1.3.0
  name: flintx-auth
  version: 1.3.0
  namespace: flintx
  port: 8081
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 100
    timeoutSeconds: 10
    successThreshold: 1
    initialDelaySeconds: 100
    httpGet:
      path: /q/health/live
      scheme: HTTP
      port: 8081
  readinessProbe:
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 100
    successThreshold: 1
    initialDelaySeconds: 100
    httpGet:
      path: /q/health/ready
      scheme: HTTP
      port: 8081