---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: e86902d1a514d1f354eb1c6ee9e1d376eed202d5
    app.quarkus.io/build-timestamp: 2023-04-06 - 00:45:04 +0000
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Values.app.version }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.port }}
  selector:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Values.app.version }}
  type: {{ .Values.app.serviceType }}
